# 编译环境、语言
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main                      # 只有 main 分支检出更改才触发 CI
before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli        # 安装 hexo
install:
  - npm install

# 执行脚本 
script:                         
  - hexo clean                  # 清除 hexo 缓存
  - hexo generate               # 生成静态文件
    # 配置域名
  - echo "www.zhaoliangyuan.com" >> public/CNAME

deploy:
  - provider: pages
    skip_cleanup: true # 跳过清理
    local_dir: public  # 需要推送到 gh-pages 分支的静态文件目录
    github_token: $gh_token # GitHub Token 变量
    keep_history: true # 保持推送记录，以增量提交的方式
    target-branch: gh-pages # 推送的目标文件夹 local_dir(public) -> gh-pages 分支
    on:
      branch: main # 工作分支
